-- Phase-1 Exploratory Analysis
-- 1. Total Revenue generated by the Food Delivery App
USE food_App_project;
SELECT SUM(order_amount-discount) AS total_revenue
FROM orders;

-- 2. Total orders Per city
SELECT r.city, COUNT(*) AS total_orders
FROM restaurants r
JOIN orders o ON r.restaurant_id = o.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC;

-- 3. Top 10 customers by spending
SELECT o.customer_id, c.name, SUM(o.order_amount) AS total_spent
FROM customers c
JOIN orders o ON c.Customer_ID = o.Customer_ID
GROUP BY o.Customer_ID, c.Name
ORDER BY total_spent DESC LIMIT 10;

-- Phase-2 Customer Segmentation
-- 4. Customer Category (Gold/Silver/Bronze)
SELECT o.customer_id, c.name, SUM(order_amount) AS total_spent,
CASE 
	WHEN SUM(order_amount) >5000 THEN 'Gold'
    WHEN SUM(order_amount) >1000 THEN 'Silver'
    ELSE 'Bronze'
END AS Category
FROM customers c 
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY o.customer_id, c.name
ORDER BY o.customer_id;

-- Phase-3 Restaurant Performance 
-- 5. Top 10 Restaurants by Revenue
SELECT r.restaurant_id, r.restaurant_name, r.city,
SUM(o.order_amount-o.discount) AS Revenue 
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city
ORDER BY Revenue DESC LIMIT 10; 

-- 6. Average Rating vs Revenue 
SELECT r.restaurant_id, SUM(o.order_amount-o.discount) AS Revenue, r.rating
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY O.restaurant_id
ORDER BY O.restaurant_id;

-- Phase-4 Delivery Analysis
-- 7. Average Delivery Time Per City
SELECT r.city, AVG(delivery_time) AS Avg_delivery_time 
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY Avg_delivery_time DESC;



-- 8. Late Deliveries (above 45 mins)
SELECT COUNT(order_id) AS late_deliveries
FROM orders
WHERE delivery_time > 45;

-- Phase-5 Payment & Discount Analysis
-- 9. Payment Method Distribution
SELECT payment_method, COUNT(*) AS count
FROM orders
GROUP BY payment_method
ORDER BY count DESC; 

-- 10. Discount Impact on Revenue
SELECT order_id, SUM(order_amount-discount) AS Revenue,
CASE 
	WHEN discount> 0 THEN 'Discounted'
    ELSE 'Non-Discounted'
END AS Discount_type
FROM orders
GROUP BY order_id;

-- Phase-6 Advanced SQL
-- 11. Monthly Revenue using CTE
WITH Monthly_Revenue AS (
    SELECT month(order_date) AS month, SUM(order_amount-discount) AS revenue
    FROM orders
    GROUP BY month )
    SELECT month, revenue
    FROM Monthly_Revenue    
    ORDER BY month;

-- 12. RANK Restaurants by Revenue
SELECT o.restaurant_id, r.restaurant_name , SUM(o.order_amount-o.discount) AS Revenue,
RANK() OVER(ORDER BY SUM(o.order_amount-o.discount) DESC) AS Revenue_rank
FROM orders o 
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY o.restaurant_id, r.restaurant_name;

-- 13. Above Average Revenue Restaurants
SELECT o.restaurant_id, r.restaurant_name, SUM(o.order_amount-o.discount) AS revenue
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY o.restaurant_id, r.restaurant_name
HAVING SUM(o.order_amount-o.discount) >
(SELECT AVG(revenue) FROM
(SELECT SUM(order_amount-discount) AS revenue
FROM orders GROUP BY restaurant_id) Avg_revenue) 
ORDER BY revenue DESC;



-- Phase-7 Database Objects
-- 14. Create Revenue View
CREATE VIEW Revenue_View AS
SELECT
    r.restaurant_id,
    r.restaurant_name,
    r.city,
    SUM(o.order_amount - o.discount) AS total_revenue   
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city;

SELECT * FROM Revenue_View;

-- 15. Stored Procedure: Get Top N Restaurants 
CREATE PROCEDURE Get_Top_N_Restaurants (IN top_n INT)   
BEGIN 
    SELECT * FROM 
        (SELECT
        r.restaurant_id,
        r.restaurant_name,
        r.city,
        SUM(o.order_amount - o.discount) AS total_revenue,
        DENSE_RANK() OVER (ORDER BY SUM(o.order_amount - o.discount) DESC) AS revenue_rank
        FROM orders o
        JOIN restaurants r ON o.restaurant_id = r.restaurant_id
        GROUP BY r.restaurant_id, r.restaurant_name, r.city) t
    WHERE revenue_rank <= top_n;
END;   

CALL Get_Top_N_Restaurants(10); 


-- Phase-8 Performance Optimization 

-- 16. Index on order_date (for monthly reports)
CREATE INDEX idx_order_date ON orders(order_date); 

-- 17. Index on customer_name (for joins)
CREATE INDEX idx_customer_name ON customers(name); 

-- 18. Index on restaurant_name (for joins)
CREATE INDEX idx_restaurant_name ON restaurants(restaurant_name);

-- Phase-9 Automation Logic

-- Auto Log High-Value Orders
CREATE TABLE high_value_log (
    log_id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    customer_id INT,
    restaurant_id INT,
    order_amount DECIMAL(10, 2),
    log_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_high_value_orders
AFTER INSERT ON orders
FOR EACH ROW
BEGIN
    IF NEW.order_amount > 1000 THEN
        INSERT INTO high_value_log (order_id, customer_id, restaurant_id, order_amount)
        VALUES (NEW.order_id, NEW.customer_id, NEW.restaurant_id, NEW.order_amount);
    END IF;
END;


INSERT INTO orders (order_id, customer_id, restaurant_id, order_date, order_amount, discount, payment_method, delivery_time) 
VALUES (1010, 231, 138, '2024-01-01', 1200.00, 100.00, 'Card', 30);
INSERT INTO orders (order_id, customer_id, restaurant_id, order_date, order_amount, discount, payment_method, delivery_time) 
VALUES (1011, 232, 139, '2024-01-02', 8000.00, 50.00, 'Cash', 25);


-- 19. TRIGGER 1 - Prevent Negative Discounts
CREATE TRIGGER trg_prevent_negative_discount
BEFORE INSERT ON orders 
FOR EACH ROW
BEGIN
    IF NEW.discount < 0 THEN
        SET NEW.discount = 0;
    END IF;
END;

INSERT INTO orders 
VALUES (1014, 231, 138, '2024-01-03', 500.00, -20.00, 'Upi', 30); 

SELECT * FROM orders WHERE order_id = 1014;
SELECT * FROM high_value_log;

-- 20. TRIGGER 2 - Delivery Delay Warning
CREATE TABLE  delivery_delay_log (
    log_id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    customer_id INT,
    restaurant_id INT,
    delivery_time INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER log_late_delivery
AFTER INSERT ON orders
FOR EACH ROW
BEGIN
    IF NEW.delivery_time > 45 THEN
        INSERT INTO delivery_delay_log (order_id, customer_id, restaurant_id, delivery_time)
        VALUES (NEW.order_id, NEW.customer_id, NEW.restaurant_id, NEW.delivery_time);
    END IF;
END;

INSERT INTO orders 
VALUES (1016, 231, 138, '2024-01-04', 600.00, 30.00, 'Card', 55);

SELECT * FROM delivery_delay_log;

